title: "Portfolio | System Engineering"
description: "Infrastructure & Cloud Specialist Portfolio"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# 한글 최적화 및 인코딩
encoding: "utf-8"
markdown: kramdown
